### PR TITLE
Open cookies portion via cookies link (Fixes #8354)

### LINKED ISSUE #8354: Cookies link in footer goes to closed accordion
## Description

https://www.mozilla.org/en-US/privacy/websites/#cookies which is linked to from the site footer does not take the user to the cookie section of the privacy policy.

### Steps to reproduce

Go to mozilla.org and click on "cookies".

### Expected result

Link to the cookie portion of the websites privacy notice.

### Actual result

View of the footer on the privacy notice.

### PR DESCRIPTION
**Pull request by mdieske**
## Description
Open the cookies portion of the website by javascript if it is visited via the cookies link. 

## Issue / Bugzilla link
#8354 

## Testing
Tested on local enviroment in different languages by clicking on "cookies" in the footer.

### CODE REVIEW

File: media/js/privacy/privacy-protocol.js [hunk 1]
```diff
@@ -19,3 +19,16 @@
         buttons[i].setAttribute('data-close', closeText);
     }
 })();
+
+if (window.location.href.includes('cookies')) {
```
Comment (alexgibson) [inline media/js/privacy/privacy-protocol.js:23]: Suggest using `window.location.hash` here to be a little more explicit:
```suggestion
if (window.location.hash === '#cookies') {
```

File: media/js/privacy/privacy-protocol.js [hunk 2]
```diff
@@ -19,3 +19,16 @@
...
+    window.onload = function() {
```
Comment (alexgibson) [inline media/js/privacy/privacy-protocol.js:24]: There should be no need to override the `onload` event handler here? Suggest moving this logic inside the closure above, together with the existing code for this page.

File: media/js/privacy/privacy-protocol.js [hunk 3]
```diff
@@ -19,3 +19,16 @@
...
+        'use strict';
+        
+        var cookieButton = document.querySelector('#user-choices button');
+        var cookieText = document.getElementById('expand-formatparagraphssummary-2');
+        
+        cookieButton.setAttribute('aria-expanded', 'true');
```
Comment (alexgibson) [inline media/js/privacy/privacy-protocol.js:30]: These lines will throw errors should the selectors above not be found, and since the HTMl on this page is generated via markdown it could be a little brittle.

To avoid throwing errors should something go wrong, I'd suggest adding a check that both selectors have found a match:

```javascript
if (cookieButton && cookieText) {
    cookieButton.setAttribute('aria-expanded', 'true');
    cookieText.classList.remove('is-closed');
    cookieText.setAttribute('aria-hidden', 'false');
}
```

File: media/js/privacy/privacy-protocol.js (hunk 1 above)
Comment (mdieske) [reply media/js/privacy/privacy-protocol.js:23]: Good suggestion, thank you!

File: media/js/privacy/privacy-protocol.js (hunk 2 above)
Comment (mdieske) [reply media/js/privacy/privacy-protocol.js:24]: You are right. Thought it was necessary but defining the variables after the existing code works also.

**Comment by mdieske** [comment]
Thank you for your feedback and suggestions @alexgibson. As I am a beginner this is very valuable for me. I'll commit your requested changes.
