### PR TITLE
Pass utm params from upstream referrals on fxa_email_form (Fixes #8001)

### LINKED ISSUE #8001: Not passing through utm parameters from upstream referrals on /firefox/accounts/
## Description

The page at www.mozilla.org/firefox/accounts/ is not passing through parameters coming from upstream referrers. It should be.

We have worked on this several times in 2019, most recently at https://github.com/mozilla/bedrock/issues/7585. We should review that work to understand if this bug relates to that in any way.

### Steps to reproduce

1. Visit about:welcome in a *Firefox Profile that is not signed in to Sync*.
2. Click the "Learn More about the Benefits" link at the bottom of the firstrun experience. 
3. Note the parameters on the URL: `https://www.mozilla.org/en-US/firefox/accounts/?utm_campaign=firstrun&utm_medium=referral&utm_source=activity-stream&utm_term=trailhead-join`
4. Fill in the Sync sign-up form (perhaps with a fake email address) and submit.
5. Note the parameters on the URL: `https://accounts.firefox.com/signup?action=email&context=fx_desktop_v3&service=sync&entrypoint=mozilla.org-firefox-accounts&form_type=email&flow_id=7c45f2ee51998ba8ae782391e1fbf4813174e8253668742d916bc0afd77fa440&flow_begin_time=1571857270270&device_id=78ad24a987b64c338da60447a29a7c70&utm_source=mozilla.org-firefox-accounts&utm_medium=referral&utm_campaign=trailhead-fxa-embedded-form&style=trailhead&email=flibbijy%40mailinator.com`\

### Expected result

The second URL should have the utm_source, utm_campaign, utm_medium, and utm_term that the first URL has. 

### Actual result

The second URL has the default utm parameters from this page.

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Refactors `mozilla-fxa-form.js` to check for utm parameters on the url before applying it's own.

## Issue / Bugzilla link
#8001

## Testing

- [x] Should apply url utm parameter values to corresponding hidden input field values if present.
- [x] If there are no utm parameters on the url, it's own values are passed.
- [x] utm parameters are validated. 

- http://localhost:8000/en-US/firefox/accounts/?utm_campaign=firstrun&utm_medium=referral&utm_source=activity-stream&utm_term=trailhead-join

Screen Shot 2019-11-11 at 3 17 25 PM

- http://localhost:8000/en-US/firefox/accounts/

Screen Shot 2019-11-11 at 3 20 11 PM

### CODE REVIEW

File: media/js/base/mozilla-fxa-form.js [hunk 1]
```diff
@@ -49,21 +48,39 @@ if (typeof window.Mozilla === 'undefined') {
...
-            var destURL = fxaForm.getAttribute('action') + 'metrics-flow';
+            // track external UTM referrals
+            var urlParams = new window._SearchParams().utmParamsFxA();
+            var attributionData = Mozilla.UtmUrl.getAttributionData(urlParams);
+
+            if (attributionData) {
+                var utms = ['utm_source', 'utm_campaign', 'utm_content', 'utm_term', 'utm_medium'];
+                for (var i = 0; i < utms.length; i++) {
+                    if (attributionData.hasOwnProperty(utms[i])) {
+                        fxaForm.querySelector(`[name="${utms[i]}"]`).value = `${attributionData[utms[i]]}`;
```
Comment (amychurchwell) [inline media/js/base/mozilla-fxa-form.js]: tests are failing due to the notation on this line: 
```
(`[name="${utms[i]}"]`).value = `${attributionData[utms[i]]}`
```
but I'm not quite sure how to achieve this without the back-ticks?

Comment (alexgibson) [reply media/js/base/mozilla-fxa-form.js]: String template literals don't yet have broad enough browser support to use natively: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

You'll probably need to use regular string concatenation instead:

```javascript
'[name="' + utms[i] + '"]'.value = attributionData[utms[i]]
```

File: media/css/firefox/accounts-2019.scss [hunk 2]
```diff
@@ -25,8 +25,6 @@
 
     .c-accounts-hero-title {
         @include text-display-lg;
-        background: transparent url('/media/protocol/img/logos/firefox/logo-word-hor.svg') center top no-repeat;
```
Comment (alexgibson) [inline media/css/firefox/accounts-2019.scss]: This seems unrelated to this issue, but if this is for https://github.com/mozilla/bedrock/issues/8118 then let's remove the logo from exp/firefox/accounts/ to?

Comment (amychurchwell) [reply media/css/firefox/accounts-2019.scss]: oh whoops, this was accidentally left in while I was filing that issue. 🤦‍♀

File: bedrock/base/templates/macros.html [hunk 3]
```diff
@@ -264,24 +264,18 @@ <h2 class="thank-you hidden">{{ _('Your download link was sent.') }}</h2>
...
     {% else %}
-      <input type="hidden" name="utm_campaign" value="fxa-embedded-form" id="fxa-email-form-utm-campaign" />
+      <input type="hidden" name="utm_campaign" value="fxa-embedded-form" />
     {% endif %}
 
     {# utm_content is optional. It should only be declared when there is new messaging associated with the form. (For example: `get-the-rest-of-firefox`) #}
-    {% if utm_content %}
-      <input type="hidden" name="utm_content" value="{{ utm_content }}" id="fxa-email-form-utm-content" />
-    {% endif %}
+    <input type="hidden" name="utm_content" value="{{ utm_content }}" id="fxa-email-form-utm-content"/>
```
Comment (alexgibson) [inline bedrock/base/templates/macros.html]: If these are no longer included conditionally, should they have default values?

File: bedrock/base/templates/macros.html [hunk 4]
```diff
@@ -264,24 +264,18 @@ <h2 class="thank-you hidden">{{ _('Your download link was sent.') }}</h2>
 
     {# utm_campaign is used to identify specific marketing campaigns. (For example: trailhead or skyline) If there is one, the campaign name is prepended to the default value of `fxa-embedded-form`. #}
     {% if utm_campaign %}
-      <input type="hidden" name="utm_campaign" value="{{ utm_campaign }}-fxa-embedded-form" id="fxa-email-form-utm-campaign" />
+      <input type="hidden" name="utm_campaign" value="{{ utm_campaign }}-fxa-embedded-form" />
     {% else %}
-      <input type="hidden" name="utm_campaign" value="fxa-embedded-form" id="fxa-email-form-utm-campaign" />
```
Comment (alexgibson) [inline bedrock/base/templates/macros.html]: I think you can still use an `id` to target the input here?

File: bedrock/base/templates/macros.html (hunk 3 above)
Comment (amychurchwell) [reply bedrock/base/templates/macros.html]: I don't think they should have default values. if `value=""` it does not get passed and it is not a required value.

Comment (alexgibson) [reply bedrock/base/templates/macros.html]: Ok as long as it doesn't get passed that should keep things nice and simple 👍

Comment (alexgibson) [reply bedrock/base/templates/macros.html]: It looks like loading the page without any utm params in the URL results in a 400 response from the metrics request:

```
GET https://latest.dev.lcip.org/metrics-flow?form_type=email&entrypoint=mozilla.org-firefox-accounts&utm_source=mozilla.org-firefox-accounts&utm_campaign=trailhead-fxa-embedded-form&utm_content=&utm_term= 400
```

The value for `utm_content` also seems to be defaulting

File: media/js/base/mozilla-fxa-form.js [hunk 5]
```diff
@@ -49,21 +48,39 @@ if (typeof window.Mozilla === 'undefined') {
 
             fxaSubmitButton.disabled = false;
 
-            var destURL = fxaForm.getAttribute('action') + 'metrics-flow';
+            // track external UTM referrals
+            var urlParams = new window._SearchParams().utmParamsFxA();
```
Comment (alexgibson) [inline media/js/base/mozilla-fxa-form.js]: The `utmParamsFxA()` function here seems to have been written some time ago, and has some strange behavior which I'm not sure we're expecting here. For example, if `utm_content` is missing from the URL then it returns the pathname (e.g. `/firefox/accounts/`) instead.

I'm not entirely convinced we should be using this function here, as it seems like an old piece of code and is no longer used anywhere on the site. I'd suggest using `utmParams()` instead, since this just returns the values without any hidden logic?

File: bedrock/base/templates/macros.html (hunk 3 above)
Comment (amychurchwell) [reply bedrock/base/templates/macros.html]: Oh shoot, you are right. Reaching out to Saptarshi for a recommendation on what a default value should be.

Comment (amychurchwell) [reply bedrock/base/templates/macros.html]: oh shoot, you are right. I spoke with Saptarshi and Justin about a potential default `utm_content` value and Justin asked why we don't insert the hidden `utm_content` input if the value is present on the URL. I thought that could potentially be a good solution-

if `utm_content` exists on URL: check that input field exists > If exists: overwrite // If does not exist: insert one.
