### PR TITLE
Fix JS error parsing malformed utm values (Fixes #10897)

### LINKED ISSUE #10897: JS error parsing malformed utm value
## Description

We see a small but steady flow of these errors in [Sentry](https://sentry.prod.mozaws.net/operations/bedrock-frontend-prod/issues/14812098/events/?environment=production).

### Steps to reproduce

1. Open https://www.mozilla.org/en-US/?utm_source=uns_footer%
2. Open the web console.

### Expected result

There should be no error.

### Actual result

```javascript
Uncaught URIError: malformed URI sequence
    getAttributionData https://www.mozilla.org/media/js/data.98cf22b6442e.js:1
    init https://www.mozilla.org/media/js/data.98cf22b6442e.js:1
    <anonymous> https://www.mozilla.org/media/js/data.98cf22b6442e.js:1
    <anonymous> https://www.mozilla.org/media/js/data.98cf22b6442e.js:1
```

### Environment

Firefox Nightly 97
macOS

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Prevents malformed utm parameter values throwing an error when parsing attribution data.

## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/10897

## Testing
Test URL: http://localhost:8000/en-US/products/vpn/?utm_source=test&utm_campaign=test&utm_contant=uns_footer%

- [ ] Page should not throw a JS error in the console.
- [ ] Both `utm_source` and `utm_campaign` should still be passed through to the subscription links in-page.
- [ ] `utm_content` should be dropped from inclusion, since the value is malformed.

### CODE REVIEW

File: media/js/base/fxa-utm-referral.js [hunk 1]
```diff
@@ -178,9 +178,13 @@ if (typeof window.Mozilla === 'undefined') {
...
-                var foundParam = decodeURIComponent(params[acceptedParam]);
-                if (allowedChars.test(foundParam)) {
-                    finalParams[acceptedParam] = foundParam;
+                try {
+                    var foundParam = decodeURIComponent(params[acceptedParam]);
+                    if (allowedChars.test(foundParam)) {
+                        finalParams[acceptedParam] = foundParam;
+                    }
+                } catch (e) {
+                    // silently drop malformed parameter values (issue #10897)
```
Comment (maureenlholland) [inline media/js/base/fxa-utm-referral.js:187]: is it worth still logging the error?

`uns_footer%` seems to be an unsubscribe footer tag that just got mixed in the email/newsletter template syntax. It feels useful to be able to alert other teams that this is failing.(But that's also tied into whether or not anyone is actually looking at the data for these tags)

**Review by maureenlholland — APPROVED** [review]
r+wc 

Works as expected, just a question of whether we want to fail silently or not

File: media/js/base/fxa-utm-referral.js (hunk 1 above)
Comment (alexgibson) [reply media/js/base/fxa-utm-referral.js:187]: My hesitation here is that these params are ultimately out of our control and can come from many different sources (including ones outside of our organisation), so I'm not really sure how actionable throwing an error here would be. We'd need to 1.) notice the error, and then 2.) figure out where it comes from and 3.) try and notify the owner.

Maybe we can figure out a system for the above in the future, but right now I think avoiding the errors (which halts the rest of the data script from running) is probably the most user-impactful thing to fix.

**Comment by alexgibson** [comment]
Thanks for the review @maureenlholland 💯
